# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Minecraft.ods.im - 我的世界资源网址导航
keywords: 网址导航
description: 资源网站
# brief-intro: Minecraft资源导航站
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://minecraft.ods.im" # the base hostname & protocol for your site

permalink: /:title/

# other links
# twitter_username:
# facebook_username: 
# github_username: ODS  
# email: 878269086@qq.com
# weibo_username: 
# zhihu_username: 
# linkedIn_username: 
# dribbble_username:
qq_username: 878269086
# description_footer: 本站记录我前端之旅的沿途风景！


# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: a2dd6d09663ba7c98593776b7a09dcda
google_analytics_id: G-TKTS6T4CT0 # google 分析追踪id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 10

plugins:
  - jekyll-paginate
